name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [docker]
    container:
      image: 192.168.1.150:5000/docker-node:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
          config-inline: |
            [registry."192.168.1.150:5000"]
              http = true
              insecure = true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./greedy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 192.168.1.150:5000/greedy:latest
          provenance: false

      - name: Notify deployment success
        if: success()
        run: |
          echo "Docker image built and pushed successfully!"
          echo "Registry: 192.168.1.150:5000/greedy:latest"
